# Generated by Django 5.2.1 on 2025-05-15 21:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('geofence_id', models.AutoField(primary_key=True, serialize=False)),
                ('radius', models.FloatField()),
                ('trigger_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('both', 'Both')], max_length=5)),
                ('action', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sent_alert', 'Send Alert'), ('recommended', 'Send Recommendation')], max_length=15), default=list, size=None)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='locations.location')),
            ],
        ),
    ]
