# Generated by Django 5.2.1 on 2025-05-15 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationRoute',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('estimated_time', models.IntegerField()),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='locations.location')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_routes', to='locations.location')),
            ],
        ),
    ]
