# Generated by Django 5.2.1 on 2025-05-15 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_recommendations', to='locations.location')),
                ('recommended_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='locations.location')),
            ],
        ),
    ]
